### ISSUE TITLE
Build fails on Windows (current master)

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/dplyr#3825]
I wanted to try the new design of hybrid and standard evaluation, but couldn't due to this error on my Windows; ``undefined reference to `std::tr1::hash<Rcomplex>::operator()(Rcomplex) const'``. I think you can see the full build log via AppVeyer, but here's some last lines in case this is useful:

``` 
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o dplyr.dll tmp.def RcppExports.o address.o api.o arrange.o between.o bind.o distinct.o encoding.o filter.o group_by.o group_indices.o init.o join.o join_exports.o mutate.o rlang-export.o rlang.o select.o set.o summarise.o test.o utils-bindings.o utils.o window.o -LC:/PROGRA~1/R/R-35~1.1/bin/x64 -lR
mutate.o:mutate.cpp:(.text$_ZNKSt3tr110_HashtableI8RcomplexS1_SaIS1_ESt9_IdentityIS1_ESt8equal_toIS1_ENS_4hashIS1_EENS_8__detail18_Mod_range_hashingENS9_20_Default_ranged_hashENS9_20_Prime_rehash_policyELb0ELb1ELb1EE5countERKS1_[_ZNKSt3tr110_HashtableI8RcomplexS1_SaIS1_ESt9_IdentityIS1_ESt8equal_toIS1_ENS_4hashIS1_EENS_8__detail18_Mod_range_hashingENS9_20_Default_ranged_hashENS9_20_Prime_rehash_policyELb0ELb1ELb1EE5countERKS1_]+0x27): undefined reference to `std::tr1::hash<Rcomplex>::operator()(Rcomplex) const'
mutate.o:mutate.cpp:(.text$_ZNSt3tr110_HashtableI8RcomplexS1_SaIS1_ESt9_IdentityIS1_ESt8equal_toIS1_ENS_4hashIS1_EENS_8__detail18_Mod_range_hashingENS9_20_Default_ranged_hashENS9_20_Prime_rehash_policyELb0ELb1ELb1EE9_M_rehashEy[_ZNSt3tr110_HashtableI8RcomplexS1_SaIS1_ESt9_IdentityIS1_ESt8equal_toIS1_ENS_4hashIS1_EENS_8__detail18_Mod_range_hashingENS9_20_Default_ranged_hashENS9_20_Prime_rehash_policyELb0ELb1ELb1EE9_M_rehashEy]+0x69): undefined reference to `std::tr1::hash<Rcomplex>::operator()(Rcomplex) const'
mutate.o:mutate.cpp:(.text$_ZNSt3tr110_HashtableI8RcomplexS1_SaIS1_ESt9_IdentityIS1_ESt8equal_toIS1_ENS_4hashIS1_EENS_8__detail18_Mod_range_hashingENS9_20_Default_ranged_hashENS9_20_Prime_rehash_policyELb0ELb1ELb1EE9_M_insertERKS1_NS_17integral_constantIbLb1EEE[_ZNSt3tr110_HashtableI8RcomplexS1_SaIS1_ESt9_IdentityIS1_ESt8equal_toIS1_ENS_4hashIS1_EENS_8__detail18_Mod_range_hashingENS9_20_Default_ranged_hashENS9_20_Prime_rehash_policyELb0ELb1ELb1EE9_M_insertERKS1_NS_17integral_constantIbLb1EEE]+0x34): undefined reference to `std::tr1::hash<Rcomplex>::operator()(Rcomplex) const'
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'dplyr'
```

I don't understand what's happening here, but, if I use `boost::unordered_map` and `boost::unordered_set` instead of `RCPP_UNORDERED_MAP` and `RCPP_UNORDERED_SET`, the build succeeded (the tests fail, though...). More precisely, removing these `if`s here:

https://github.com/tidyverse/dplyr/blob/53ed25b65a8db4b619ad7212863c6532b66c8021/inst/include/tools/hash.h#L7-L9

https://github.com/tidyverse/dplyr/blob/53ed25b65a8db4b619ad7212863c6532b66c8021/inst/include/tools/hash.h#L16-L18

`RCPP_UNORDERED_MAP` and `RCPP_UNORDERED_SET` were introduced in https://github.com/tidyverse/dplyr/commit/f82f55d8337f1bccc9f6f0e751639f42dfca62f8, which addresses https://github.com/tidyverse/dplyr/issues/114#issuecomment-28428103. Is this workaround still needed? Note that I'm using Rtools 3.5, so I don't know if this works on the older version of R on Windows.

**Comment by krlmlr** [comment]
Seeing this in AppVeyor too: https://ci.appveyor.com/project/tidyverse/dplyr/build/job/87ccp0ghua4wknut/artifacts. Setting up a larger build matrix to test potential solutions as part of #2295.

**Comment by krlmlr** [comment]
Relevant build, still running: https://ci.appveyor.com/project/tidyverse/dplyr/build/1.0.1722

**Comment by yutannihilation** [comment]
Shouldn't `${DPLYR_COMPILER_FLAGS}` be added to `Makevars.win` as well...?

**Comment by krlmlr** [comment]
Good catch, thanks!

**Comment by krlmlr** [comment]
I just noticed that testing on old versions of R requires installing almost everything from source.

@hadley: Do we also support up to R 3.1 on Windows, or only release and oldrel?

**Comment by krlmlr** [comment]
@yutannihilation: Maybe we just need to provide a hash function: https://stackoverflow.com/a/1891340/946850? Perhaps this is even an _Rcpp_ problem?

**Comment by yutannihilation** [comment]
@krlmlr 

> Perhaps this is even an Rcpp problem?

I'm not really sure which is responsible for this, Rcpp or dplyr. But, it seems you are right, Rcpp only provides hash function for `Rcpp::String`.

https://github.com/RcppCore/Rcpp/blob/f3c5a34e06e774532227470b01c63a8f08ce4313/inst/include/Rcpp/sugar/sets.h#L39-L53

(One big mystery to me is that why this worked without the definition so far...)

**Comment by yutannihilation** [comment]
If I implemented a hash function for `Rcomplex` in ` inst/include/tools/hash.h`, the build passes. It seems we need to define `hash_combine()` by ourselves since `std::` doesn't have it.

https://github.com/yutannihilation/dplyr/pull/1/files

But..., still I don't think I can propose a PR for Rcpp, since I don't really understand the problem....

**Comment by krlmlr** [comment]
Thanks! I think we need to start with adding a hash function here, and then see if we can fix it for _Rcpp_. PR welcome ;-)

**Comment by yutannihilation** [comment]
Thanks, I will try.

What should I do for `hash_combine()`? Can we use `boost::hash_combine()` in dplyr? If I have to copy and paste the code from boost, I think I need to license it properly.

**Comment by yutannihilation** [comment]
No, I don't think it's needed. Thanks.
