### ISSUE TITLE
dplyr 0.7.0 for OS X El Capitan not available in CRAN (test fails)

### ISSUE THREAD

**Issue by zeehio** [tidyverse/dplyr#2862]
dplyr 0.7.0 is not available in CRAN for OSX El Capitan due to failing tests. Questions related to this have already started to pop up in [stackoverflow](https://stackoverflow.com/questions/44489188/errors-installing-dplyr-in-r).

I hope you are aware of this situation, I assumed you were but with the publication of https://blog.rstudio.org/2017/06/13/dplyr-0-7-0/ I am not so sure.

The failing tests seem to be `desc()` related:

```
  1. Failure: row_number(), ntile(), min_rank(), percent_rank(), dense_rank(), and cume_dist() work (@test-hybrid.R#413)
  2. Failure: desc is correctly handled by window functions (@test-mutate-windowed.R#9)
  3. Failure: desc is correctly handled by window functions (@test-mutate-windowed.R#10)
  4. Failure: row_number gives correct results (@test-mutate-windowed.R#17)
  5. Failure: rank functions deal correctly with NA (#774) (@test-mutate-windowed.R#113)
  6. Failure: rank functions deal correctly with NA (#774) (@test-mutate-windowed.R#120)
  7. Failure: rank functions deal correctly with NA (#774) (@test-mutate-windowed.R#141)
  8. Failure: rank functions deal correctly with NA (#774) (@test-mutate-windowed.R#148) 
```

More details on failing tests at the [CRAN results](https://cran.r-project.org/web/checks/check_results_dplyr.html)

Sorry for disturbing if you are already aware. I would try to help to fix this, but I don't have a Mac.

**Comment by hadley** [comment]
I didn't see that because it works for me, and mac CRAN doesn't automatically notify on failure 😢 We're working on a patch release ASAP.

**Comment by vnijs** [comment]
Since this issue's close date seems to be **before** the latest CRAN test results I'm wondering if the build for El Capitan might have failed again? FYI source build on El Capitan seems to work fine

[CRAN results](https://cran.r-project.org/web/checks/check_results_dplyr.html): "using R version 3.4.0 Patched (2017-06-15 r72796)"

**Comment by zeehio** [comment]
Until there is a new CRAN source submission (with greater dplyr version, e.g. 0.7.1) the CRAN results will continue failing. The "Last update" time they report in the cran results page changes when they rerun the checks, usually because any of the systems they use for testing has been updated.

While I may be wrong about this, I don't think there is new relevant information there right now... But thanks for the warning

**Comment by wabee** [comment]
Still fails to compile on macOS Sierra and R 3.40

**Comment by zeehio** [comment]
The CRAN results I see https://cran.rstudio.com/web/checks/check_results_dplyr.html are still showing 0.7.0 compilation results for r-release-osx-x86_64. None of the platforms with 0.7.1 compiled show an error. @wabee, what compilation error do you see for 0.7.1?

**Comment by vnijs** [comment]
FYI 0.7.1 was published on 6/22 but there is no build for El Capitan yet on 7/3. No test results either. Seems odd

https://cran.r-project.org/web/checks/check_results_dplyr.html

**Comment by wabee** [comment]
I received 0.7.1 on Sierra about a Week ago

**Comment by zeehio** [comment]
This is not a dplyr specific issue https://cran.r-project.org/web/checks/check_results_glue.html https://cran.r-project.org/web/checks/check_results_covr.html

I don't know what is going on.

**Comment by rashmimehrotra** [comment]
dplyr 0.7.1 seems does not work with R version 3.4.1.. as my working functions on dplyr 0.7.1 broke as soon as I transfer them to a mac with the latest R (3.4.1). Any idea what's going on?

**Comment by hadley** [comment]
@rashmimehrotra please open a new issue with a reproducible example/`traceback()`.
