### ISSUE TITLE
dplyr and g++ 4.4

### ISSUE THREAD

**Issue by grvalex** [tidyverse/dplyr#116]
Sorry if this is a duplicate, but I can't find the issue I opened this morning so I'm working off the assumption github ate it.  Feel free to merge them if it is.

I'm unable to build dplyr with g++ 4.4.  I've tested on Ubuntu 12.04 and I can build fine with g++ 4.6, but not 4.4.  Unfortunately 4.4 is the version Ubuntu 10.04 ships with.

Here are the g++ errors.  Any help aside from upgrading the OS or g++ would be great:
11:27:04 g++ -I/usr/share/R/include -DNDEBUG -I../inst/include/  -I"/usr/lib/R/addOnPackages-CRAN/Rcpp/include" -I"/usr/lib/R/addOnPackages-CRAN/BH/include"   -fpic  -O3 -pipe  -g  -c RcppExports.cpp -o RcppExports.o
11:27:08 In file included from ../inst/include/dplyr.h:54,
11:27:08                  from RcppExports.cpp:5:
11:27:08 ../inst/include/dplyr/VectorVisitorImpl.h: In member function ‘virtual std::string dplyr::FactorVisitor::get_r_type() const’:
11:27:08 ../inst/include/dplyr/VectorVisitorImpl.h:189: error: ‘template<int RTYPE> class dplyr::VectorVisitorImpl’ used without template parameters
11:27:08 ../inst/include/dplyr/VectorVisitorImpl.h: In constructor ‘dplyr::DateVisitor::DateVisitor(const Rcpp::NumericVector&)’:
11:27:08 ../inst/include/dplyr/VectorVisitorImpl.h:225: error: class ‘dplyr::DateVisitor’ does not have any field named ‘PromoteClassVisitor’
11:27:08 ../inst/include/dplyr/VectorVisitorImpl.h:225: error: no matching function for call to ‘dplyr::PromoteClassVisitor<dplyr::DateVisitor, dplyr::VectorVisitorImpl<14> >::PromoteClassVisitor()’
11:27:08 ../inst/include/dplyr/VectorVisitorImpl.h:113: note: candidates are: dplyr::PromoteClassVisitor<Class, VisitorImpl>::PromoteClassVisitor(const typename VisitorImpl::VECTOR&) [with Class = dplyr::DateVisitor, VisitorImpl = dplyr::VectorVisitorImpl<14>]
11:27:08 ../inst/include/dplyr/VectorVisitorImpl.h:110: note:                 dplyr::PromoteClassVisitor<dplyr::DateVisitor, dplyr::VectorVisitorImpl<14> >::PromoteClassVisitor(const dplyr::PromoteClassVisitor<dplyr::DateVisitor, dplyr::VectorVisitorImpl<14> >&)
11:27:08 ../inst/include/dplyr/VectorVisitorImpl.h: In constructor ‘dplyr::POSIXctVisitor::POSIXctVisitor(const Rcpp::NumericVector&)’:
11:27:08 ../inst/include/dplyr/VectorVisitorImpl.h:226: error: class ‘dplyr::POSIXctVisitor’ does not have any field named ‘PromoteClassVisitor’
11:27:08 ../inst/include/dplyr/VectorVisitorImpl.h:226: error: no matching function for call to ‘dplyr::PromoteClassVisitor<dplyr::POSIXctVisitor, dplyr::VectorVisitorImpl<14> >::PromoteClassVisitor()’
11:27:08 ../inst/include/dplyr/VectorVisitorImpl.h:113: note: candidates are: dplyr::PromoteClassVisitor<Class, VisitorImpl>::PromoteClassVisitor(const typename VisitorImpl::VECTOR&) [with Class = dplyr::POSIXctVisitor, VisitorImpl = dplyr::VectorVisitorImpl<14>]
11:27:08 ../inst/include/dplyr/VectorVisitorImpl.h:110: note:                 dplyr::PromoteClassVisitor<dplyr::POSIXctVisitor, dplyr::VectorVisitorImpl<14> >::PromoteClassVisitor(const dplyr::PromoteClassVisitor<dplyr::POSIXctVisitor, dplyr::VectorVisitorImpl<14> >&)
11:27:08 In file included from ../inst/include/dplyr.h:58,
11:27:08                  from RcppExports.cpp:5:
11:27:08 ../inst/include/dplyr/JoinVisitorImpl.h: In member function ‘bool dplyr::StringLessPredicate::operator()(SEXPREC_, SEXPREC_)’:
11:27:08 ../inst/include/dplyr/JoinVisitorImpl.h:58: error: ‘template<int RTYPE> struct dplyr::comparisons’ used without template parameters
11:27:08 ../inst/include/dplyr/JoinVisitorImpl.h: In constructor ‘dplyr::DateJoinVisitor::DateJoinVisitor(const Rcpp::NumericVector&, const Rcpp::NumericVector&)’:
11:27:08 ../inst/include/dplyr/JoinVisitorImpl.h:188: error: class ‘dplyr::DateJoinVisitor’ does not have any field named ‘PromoteClassJoinVisitor’
11:27:08 ../inst/include/dplyr/JoinVisitorImpl.h:188: error: no matching function for call to ‘dplyr::PromoteClassJoinVisitor<dplyr::DateJoinVisitor, dplyr::JoinVisitorImpl<14> >::PromoteClassJoinVisitor()’
11:27:08 ../inst/include/dplyr/JoinVisitorImpl.h:165: note: candidates are: dplyr::PromoteClassJoinVisitor<Class, JoinVisitorImpl>::PromoteClassJoinVisitor(const typename JoinVisitorImpl::Vec&, const typename JoinVisitorImpl::Vec&) [with Class = dplyr::DateJoinVisitor, JoinVisitorImpl = dplyr::JoinVisitorImpl<14>]
11:27:08 ../inst/include/dplyr/JoinVisitorImpl.h:161: note:                 dplyr::PromoteClassJoinVisitor<dplyr::DateJoinVisitor, dplyr::JoinVisitorImpl<14> >::PromoteClassJoinVisitor(const dplyr::PromoteClassJoinVisitor<dplyr::DateJoinVisitor, dplyr::JoinVisitorImpl<14> >&)
11:27:08 ../inst/include/dplyr/JoinVisitorImpl.h: In constructor ‘dplyr::POSIXctJoinVisitor::POSIXctJoinVisitor(const Rcpp::NumericVector&, const Rcpp::NumericVector&)’:
11:27:08 ../inst/include/dplyr/JoinVisitorImpl.h:189: error: class ‘dplyr::POSIXctJoinVisitor’ does not have any field named ‘PromoteClassJoinVisitor’
11:27:08 ../inst/include/dplyr/JoinVisitorImpl.h:189: error: no matching function for call to ‘dplyr::PromoteClassJoinVisitor<dplyr::POSIXctJoinVisitor, dplyr::JoinVisitorImpl<14> >::PromoteClassJoinVisitor()’
11:27:08 ../inst/include/dplyr/JoinVisitorImpl.h:165: note: candidates are: dplyr::PromoteClassJoinVisitor<Class, JoinVisitorImpl>::PromoteClassJoinVisitor(const typename JoinVisitorImpl::Vec&, const typename JoinVisitorImpl::Vec&) [with Class = dplyr::POSIXctJoinVisitor, JoinVisitorImpl = dplyr::JoinVisitorImpl<14>]
11:27:08 ../inst/include/dplyr/JoinVisitorImpl.h:161: note:                 dplyr::PromoteClassJoinVisitor<dplyr::POSIXctJoinVisitor, dplyr::JoinVisitorImpl<14> >::PromoteClassJoinVisitor(const dplyr::PromoteClassJoinVisitor<dplyr::POSIXctJoinVisitor, dplyr::JoinVisitorImpl<14> >&)
11:27:08 In file included from ../inst/include/dplyr.h:62,
11:27:08                  from RcppExports.cpp:5:
11:27:08 ../inst/include/dplyr/Collecter.h: In constructor ‘dplyr::POSIXctCollecter::POSIXctCollecter(int)’:
11:27:08 ../inst/include/dplyr/Collecter.h:73: error: class ‘dplyr::POSIXctCollecter’ does not have any field named ‘TypedCollecter’
11:27:08 ../inst/include/dplyr/Collecter.h:73: error: no matching function for call to ‘dplyr::TypedCollecter<14>::TypedCollecter()’
11:27:08 ../inst/include/dplyr/Collecter.h:49: note: candidates are: dplyr::TypedCollecter<RTYPE>::TypedCollecter(int, Rcpp::CharacterVector) [with int RTYPE = 14]
11:27:08 ../inst/include/dplyr/Collecter.h:47: note:                 dplyr::TypedCollecter<14>::TypedCollecter(const dplyr::TypedCollecter<14>&)
11:27:08 ../inst/include/dplyr/Collecter.h: In constructor ‘dplyr::DateCollecter::DateCollecter(int)’:
11:27:08 ../inst/include/dplyr/Collecter.h:78: error: class ‘dplyr::DateCollecter’ does not have any field named ‘TypedCollecter’
11:27:08 ../inst/include/dplyr/Collecter.h:78: error: no matching function for call to ‘dplyr::TypedCollecter<14>::TypedCollecter()’
11:27:08 ../inst/include/dplyr/Collecter.h:49: note: candidates are: dplyr::TypedCollecter<RTYPE>::TypedCollecter(int, Rcpp::CharacterVector) [with int RTYPE = 14]
11:27:08 ../inst/include/dplyr/Collecter.h:47: note:                 dplyr::TypedCollecter<14>::TypedCollecter(const dplyr::TypedCollecter<14>&)
11:27:09 make: **\* [RcppExports.o] Error 1
11:27:09 ERROR: compilation failed for package ‘dplyr’
