### PR TITLE
Depend on Rcpp >= 0.12.7

### LINKED ISSUE #2902: dplyr wont compile on R3.4
* installing *source* package 'dplyr' ...
** package 'dplyr' successfully unpacked and MD5 sums checked
** libs
g++ -m64  -I/usr/include/R -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/usr/lib64/R/library/bindrcpp/include" -I"/usr/lib64/R/library/plogr/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c RcppExports.cpp -o RcppExports.o
In file included from ../inst/include/tools/Quosure.h:4,
                 from ../inst/include/tools/tools.h:9,
                 from ../inst/include/dplyr.h:6,
                 from RcppExports.cpp:4:
../inst/include/tools/SymbolString.h: In constructor 'dplyr::SymbolString::SymbolString(const Rcpp::Symbol&)':
../inst/include/tools/SymbolString.h:21: error: no matching function for call to 'Rcpp::String::String(const char*, cetype_t)'
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:159: note: candidates are: Rcpp::String::String(Rbyte)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:158: note:                 Rcpp::String::String(Rcomplex)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:157: note:                 Rcpp::String::String(bool)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:156: note:                 Rcpp::String::String(double)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:155: note:                 Rcpp::String::String(int)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:149: note:                 Rcpp::String::String(const wchar_t*)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:144: note:                 Rcpp::String::String(const char*)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:138: note:                 Rcpp::String::String(const std::wstring&)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:133: note:                 Rcpp::String::String(const std::string&)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:126: note:                 Rcpp::String::String(const Rcpp::String::const_StringProxy&, const std::string&)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:121: note:                 Rcpp::String::String(const Rcpp::String::const_StringProxy&)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:114: note:                 Rcpp::String::String(const Rcpp::String::StringProxy&, const std::string&)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:109: note:                 Rcpp::String::String(const Rcpp::String::StringProxy&)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:91: note:                 Rcpp::String::String(SEXPREC*, const std::string&)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:74: note:                 Rcpp::String::String(SEXPREC*)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:67: note:                 Rcpp::String::String(const Rcpp::String&, const std::string&)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:62: note:                 Rcpp::String::String(const Rcpp::String&)
/usr/lib64/R/library/Rcpp/include/Rcpp/String.h:56: note:                 Rcpp::String::String()
RcppExports.cpp: In function 'SEXPREC* dplyr_get_date_classes_try()':
RcppExports.cpp:267: warning: unused variable 'rcpp_output_type'
RcppExports.cpp:267: warning: unused variable 'rcpp_output_condition'
RcppExports.cpp: In function 'SEXPREC* dplyr_get_time_classes_try()':
RcppExports.cpp:296: warning: unused variable 'rcpp_output_type'
RcppExports.cpp:296: warning: unused variable 'rcpp_output_condition'
RcppExports.cpp: In function 'SEXPREC* dplyr_build_index_cpp_try(SEXPREC*)':
RcppExports.cpp:325: warning: unused variable 'rcpp_output_type'
RcppExports.cpp:325: warning: unused variable 'rcpp_output_condition'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package 'dplyr'
* removing '/usr/lib64/R/library/dplyr'

### PR DESCRIPTION
**Pull request by zeehio**
This line in dplyr https://github.com/tidyverse/dplyr/blob/master/inst/include/tools/SymbolString.h#L21 uses `Rcpp::String::String(const char*, cetype_t)`, available in Rcpp since this commit https://github.com/RcppCore/Rcpp/commit/0bf8e97e46ff85d02d7f158c6b476369f7912cc1 that was included in 0.12.7.

That's why dplyr needs to depend on Rcpp 0.12.7 instead of 0.12.6.

Closes #2902

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks!
